#! /bin/sh

. ./prelude

enigmac wm -a "TEST-TRANSFER-A" 1024x512+0+0
enigmac wm -a "TEST-TRANSFER-B" 1024x512+0+512

enigmac monitor "TEST-TRANSFER-A" -a source
enigmac monitor -f "TEST-TRANSFER-A"

window add 3

root_rectangle_y=$(enigmac query -T -n @/ | jshon -e rectangle -e y)

enigmac desktop "TEST-TRANSFER-A:focused" -m "TEST-TRANSFER-B"

[ "$(enigmac query -D -m "TEST-TRANSFER-A" | wc -l)" -eq 1 ] || fail "Invalid number of desktop in source after transfer."

enigmac desktop "TEST-TRANSFER-B:^2" -f

[ "$(enigmac query -T -n @/ | jshon -e rectangle -e y)" -ne "$root_rectangle_y" ] || fail "Wrong tiled rectangle for root in destination."

window remove 3

enigmac monitor "TEST-TRANSFER-A" -r
enigmac monitor "TEST-TRANSFER-B" -r
