#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

enigmac monitor -d 1 2 3 4 5 6 7 8 9 10

enigmac config border_width         2
enigmac config window_gap          12

enigmac config split_ratio          0.50
enigmac config borderless_monocle   true
enigmac config gapless_monocle      true
